name: dodamdodam_fe
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_riverpod: ^3.0.0
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.1
  go_router: ^16.2.4
  http: ^1.5.0
  riverpod_annotation: ^3.0.0


dev_dependencies:
  riverpod_generator: ^3.0.0
  build_runner: ^2.7.1
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.0



flutter:
  uses-material-design: true

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard/PretendardVariable.ttf

  assets:
    - .env
    - assets/images/
    - assets/icons/
    